version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gateway:
    image: aznu/micro-realestate-buying
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      REALESTATE_KAFKA_SERVER: kafka:9092
      REALESTATE_SERVICE_TYPE: gateway
  realestate:
    image: aznu/micro-realestate-buying
    depends_on:
      - kafka
    environment:
      REALESTATE_KAFKA_SERVER: kafka:9092
      REALESTATE_SERVICE_TYPE: realestate
  credit:
    image: aznu/micro-realestate-buying
    depends_on:
      - kafka
    environment:
      REALESTATE_KAFKA_SERVER: kafka:9092
      REALESTATE_SERVICE_TYPE: credit
  signcontract:
    image: aznu/micro-realestate-buying
    depends_on:
      - kafka
    environment:
      REALESTATE_KAFKA_SERVER: kafka:9092
      REALESTATE_SERVICE_TYPE: signcontract

