/*
 * Buying RealEstate mircro service
 * Micro service to buy a real estate and get credit
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.realEstate.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.bp.realEstate.model.RealEstateInfo;
/**
 * BookRealEstateRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T13:34:51.739596669+01:00[Europe/Warsaw]")
public class BookRealEstateRequest {
  @JsonProperty("realEstateInfo")
  private RealEstateInfo realEstateInfo = null;

  public BookRealEstateRequest realEstateInfo(RealEstateInfo realEstateInfo) {
    this.realEstateInfo = realEstateInfo;
    return this;
  }

   /**
   * Get realEstateInfo
   * @return realEstateInfo
  **/
  public RealEstateInfo getRealEstateInfo() {
    return realEstateInfo;
  }

  public void setRealEstateInfo(RealEstateInfo realEstateInfo) {
    this.realEstateInfo = realEstateInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookRealEstateRequest bookRealEstateRequest = (BookRealEstateRequest) o;
    return Objects.equals(this.realEstateInfo, bookRealEstateRequest.realEstateInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(realEstateInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookRealEstateRequest {\n");
    
    sb.append("    realEstateInfo: ").append(toIndentedString(realEstateInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
