/*
 * Buying RealEstate mircro service
 * Micro service to buy a real estate and get credit
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.realEstate.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
/**
 * CreditInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T13:34:51.739596669+01:00[Europe/Warsaw]")
public class CreditInfo {
  @JsonProperty("lendingRateInPercent")
  private Integer lendingRateInPercent = null;

  @JsonProperty("howManyMonths")
  private Integer howManyMonths = null;

  @JsonProperty("monthPayment")
  private Integer monthPayment = null;

  @JsonProperty("creditVolume")
  private Integer creditVolume = null;

  @JsonProperty("firstPaymentDate")
  private OffsetDateTime firstPaymentDate = null;

  public CreditInfo lendingRateInPercent(Integer lendingRateInPercent) {
    this.lendingRateInPercent = lendingRateInPercent;
    return this;
  }

   /**
   * Get lendingRateInPercent
   * @return lendingRateInPercent
  **/
  public Integer getLendingRateInPercent() {
    return lendingRateInPercent;
  }

  public void setLendingRateInPercent(Integer lendingRateInPercent) {
    this.lendingRateInPercent = lendingRateInPercent;
  }

  public CreditInfo howManyMonths(Integer howManyMonths) {
    this.howManyMonths = howManyMonths;
    return this;
  }

   /**
   * Get howManyMonths
   * @return howManyMonths
  **/
  public Integer getHowManyMonths() {
    return howManyMonths;
  }

  public void setHowManyMonths(Integer howManyMonths) {
    this.howManyMonths = howManyMonths;
  }

  public CreditInfo monthPayment(Integer monthPayment) {
    this.monthPayment = monthPayment;
    return this;
  }

   /**
   * Get monthPayment
   * @return monthPayment
  **/
  public Integer getMonthPayment() {
    return monthPayment;
  }

  public void setMonthPayment(Integer monthPayment) {
    this.monthPayment = monthPayment;
  }

  public CreditInfo creditVolume(Integer creditVolume) {
    this.creditVolume = creditVolume;
    return this;
  }

   /**
   * Get creditVolume
   * @return creditVolume
  **/
  public Integer getCreditVolume() {
    return creditVolume;
  }

  public void setCreditVolume(Integer creditVolume) {
    this.creditVolume = creditVolume;
  }

  public CreditInfo firstPaymentDate(OffsetDateTime firstPaymentDate) {
    this.firstPaymentDate = firstPaymentDate;
    return this;
  }

   /**
   * Get firstPaymentDate
   * @return firstPaymentDate
  **/
  public OffsetDateTime getFirstPaymentDate() {
    return firstPaymentDate;
  }

  public void setFirstPaymentDate(OffsetDateTime firstPaymentDate) {
    this.firstPaymentDate = firstPaymentDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditInfo creditInfo = (CreditInfo) o;
    return Objects.equals(this.lendingRateInPercent, creditInfo.lendingRateInPercent) &&
        Objects.equals(this.howManyMonths, creditInfo.howManyMonths) &&
        Objects.equals(this.monthPayment, creditInfo.monthPayment) &&
        Objects.equals(this.creditVolume, creditInfo.creditVolume) &&
        Objects.equals(this.firstPaymentDate, creditInfo.firstPaymentDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lendingRateInPercent, howManyMonths, monthPayment, creditVolume, firstPaymentDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditInfo {\n");
    
    sb.append("    lendingRateInPercent: ").append(toIndentedString(lendingRateInPercent)).append("\n");
    sb.append("    howManyMonths: ").append(toIndentedString(howManyMonths)).append("\n");
    sb.append("    monthPayment: ").append(toIndentedString(monthPayment)).append("\n");
    sb.append("    creditVolume: ").append(toIndentedString(creditVolume)).append("\n");
    sb.append("    firstPaymentDate: ").append(toIndentedString(firstPaymentDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
