/*
 * Buying RealEstate mircro service
 * Micro service to buy a real estate and get credit
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.realEstate.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * CreditRecipientInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-12T13:34:51.739596669+01:00[Europe/Warsaw]")
public class CreditRecipientInfo {
  @JsonProperty("numberOfCreditRecipient")
  private Integer numberOfCreditRecipient = null;

  @JsonProperty("sumIncomeYear")
  private Integer sumIncomeYear = null;

  @JsonProperty("numberCurrentlyOwningProperties")
  private Integer numberCurrentlyOwningProperties = null;

  @JsonProperty("sumSpendingYear")
  private Integer sumSpendingYear = null;

  @JsonProperty("sumChildren")
  private Integer sumChildren = null;

  @JsonProperty("mainRecipientFirstName")
  private String mainRecipientFirstName = null;

  @JsonProperty("mainRecipientLastName")
  private String mainRecipientLastName = null;

  @JsonProperty("mainRecipientTelefonNumber")
  private Integer mainRecipientTelefonNumber = null;

  @JsonProperty("mainRecipientPesel")
  private Integer mainRecipientPesel = null;

  public CreditRecipientInfo numberOfCreditRecipient(Integer numberOfCreditRecipient) {
    this.numberOfCreditRecipient = numberOfCreditRecipient;
    return this;
  }

   /**
   * Get numberOfCreditRecipient
   * @return numberOfCreditRecipient
  **/
  public Integer getNumberOfCreditRecipient() {
    return numberOfCreditRecipient;
  }

  public void setNumberOfCreditRecipient(Integer numberOfCreditRecipient) {
    this.numberOfCreditRecipient = numberOfCreditRecipient;
  }

  public CreditRecipientInfo sumIncomeYear(Integer sumIncomeYear) {
    this.sumIncomeYear = sumIncomeYear;
    return this;
  }

   /**
   * Get sumIncomeYear
   * @return sumIncomeYear
  **/
  public Integer getSumIncomeYear() {
    return sumIncomeYear;
  }

  public void setSumIncomeYear(Integer sumIncomeYear) {
    this.sumIncomeYear = sumIncomeYear;
  }

  public CreditRecipientInfo numberCurrentlyOwningProperties(Integer numberCurrentlyOwningProperties) {
    this.numberCurrentlyOwningProperties = numberCurrentlyOwningProperties;
    return this;
  }

   /**
   * Get numberCurrentlyOwningProperties
   * @return numberCurrentlyOwningProperties
  **/
  public Integer getNumberCurrentlyOwningProperties() {
    return numberCurrentlyOwningProperties;
  }

  public void setNumberCurrentlyOwningProperties(Integer numberCurrentlyOwningProperties) {
    this.numberCurrentlyOwningProperties = numberCurrentlyOwningProperties;
  }

  public CreditRecipientInfo sumSpendingYear(Integer sumSpendingYear) {
    this.sumSpendingYear = sumSpendingYear;
    return this;
  }

   /**
   * Get sumSpendingYear
   * @return sumSpendingYear
  **/
  public Integer getSumSpendingYear() {
    return sumSpendingYear;
  }

  public void setSumSpendingYear(Integer sumSpendingYear) {
    this.sumSpendingYear = sumSpendingYear;
  }

  public CreditRecipientInfo sumChildren(Integer sumChildren) {
    this.sumChildren = sumChildren;
    return this;
  }

   /**
   * Get sumChildren
   * @return sumChildren
  **/
  public Integer getSumChildren() {
    return sumChildren;
  }

  public void setSumChildren(Integer sumChildren) {
    this.sumChildren = sumChildren;
  }

  public CreditRecipientInfo mainRecipientFirstName(String mainRecipientFirstName) {
    this.mainRecipientFirstName = mainRecipientFirstName;
    return this;
  }

   /**
   * Get mainRecipientFirstName
   * @return mainRecipientFirstName
  **/
  public String getMainRecipientFirstName() {
    return mainRecipientFirstName;
  }

  public void setMainRecipientFirstName(String mainRecipientFirstName) {
    this.mainRecipientFirstName = mainRecipientFirstName;
  }

  public CreditRecipientInfo mainRecipientLastName(String mainRecipientLastName) {
    this.mainRecipientLastName = mainRecipientLastName;
    return this;
  }

   /**
   * Get mainRecipientLastName
   * @return mainRecipientLastName
  **/
  public String getMainRecipientLastName() {
    return mainRecipientLastName;
  }

  public void setMainRecipientLastName(String mainRecipientLastName) {
    this.mainRecipientLastName = mainRecipientLastName;
  }

  public CreditRecipientInfo mainRecipientTelefonNumber(Integer mainRecipientTelefonNumber) {
    this.mainRecipientTelefonNumber = mainRecipientTelefonNumber;
    return this;
  }

   /**
   * Get mainRecipientTelefonNumber
   * @return mainRecipientTelefonNumber
  **/
  public Integer getMainRecipientTelefonNumber() {
    return mainRecipientTelefonNumber;
  }

  public void setMainRecipientTelefonNumber(Integer mainRecipientTelefonNumber) {
    this.mainRecipientTelefonNumber = mainRecipientTelefonNumber;
  }

  public CreditRecipientInfo mainRecipientPesel(Integer mainRecipientPesel) {
    this.mainRecipientPesel = mainRecipientPesel;
    return this;
  }

   /**
   * Get mainRecipientPesel
   * @return mainRecipientPesel
  **/
  public Integer getMainRecipientPesel() {
    return mainRecipientPesel;
  }

  public void setMainRecipientPesel(Integer mainRecipientPesel) {
    this.mainRecipientPesel = mainRecipientPesel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditRecipientInfo creditRecipientInfo = (CreditRecipientInfo) o;
    return Objects.equals(this.numberOfCreditRecipient, creditRecipientInfo.numberOfCreditRecipient) &&
        Objects.equals(this.sumIncomeYear, creditRecipientInfo.sumIncomeYear) &&
        Objects.equals(this.numberCurrentlyOwningProperties, creditRecipientInfo.numberCurrentlyOwningProperties) &&
        Objects.equals(this.sumSpendingYear, creditRecipientInfo.sumSpendingYear) &&
        Objects.equals(this.sumChildren, creditRecipientInfo.sumChildren) &&
        Objects.equals(this.mainRecipientFirstName, creditRecipientInfo.mainRecipientFirstName) &&
        Objects.equals(this.mainRecipientLastName, creditRecipientInfo.mainRecipientLastName) &&
        Objects.equals(this.mainRecipientTelefonNumber, creditRecipientInfo.mainRecipientTelefonNumber) &&
        Objects.equals(this.mainRecipientPesel, creditRecipientInfo.mainRecipientPesel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfCreditRecipient, sumIncomeYear, numberCurrentlyOwningProperties, sumSpendingYear, sumChildren, mainRecipientFirstName, mainRecipientLastName, mainRecipientTelefonNumber, mainRecipientPesel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditRecipientInfo {\n");
    
    sb.append("    numberOfCreditRecipient: ").append(toIndentedString(numberOfCreditRecipient)).append("\n");
    sb.append("    sumIncomeYear: ").append(toIndentedString(sumIncomeYear)).append("\n");
    sb.append("    numberCurrentlyOwningProperties: ").append(toIndentedString(numberCurrentlyOwningProperties)).append("\n");
    sb.append("    sumSpendingYear: ").append(toIndentedString(sumSpendingYear)).append("\n");
    sb.append("    sumChildren: ").append(toIndentedString(sumChildren)).append("\n");
    sb.append("    mainRecipientFirstName: ").append(toIndentedString(mainRecipientFirstName)).append("\n");
    sb.append("    mainRecipientLastName: ").append(toIndentedString(mainRecipientLastName)).append("\n");
    sb.append("    mainRecipientTelefonNumber: ").append(toIndentedString(mainRecipientTelefonNumber)).append("\n");
    sb.append("    mainRecipientPesel: ").append(toIndentedString(mainRecipientPesel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
